spring:
  application:
    name: springboot-dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.3.99:2181
server:
  port: 18090