server:
  error:
    include-message: always
  port: 8090

spring:
  application:
    name: springboot-dubbo-consumer

dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: zookeeper://192.168.3.99:2181
